<?php
/**
 * Created by PhpStorm.
 * User: mrqi
 * Date: 2020/12/18
 * Time: 10:12
 */
namespace common\components;


use common\utils\AjaxUtil;
use common\utils\SecurityUtil;
use Yii;
use yii\web\Controller;

class sdpBaseController extends Controller
{
    public $enableCsrfValidation = false; //crf验证


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 所有操作的action都要求先登录后台
     */
    public function beforeAction($action){

        $token = $this->getParam('token');
        #Yii::$app->response->format = yii\web\Response::FORMAT_JSON;


        return parent::beforeAction($action);
    }




    /**
     * 获取参数的方法，需要对传入的参数做有效性验证
     * @param string $name 参数名
     * @param type $defaultValue 默认的缺省值
     * @param string $type 类型
     * @throws Exception 不符数据类型时抛异常
     * @return type 验证和过滤后的值
     */
    public function getParam($name,$defaultValue = NULL,$type="string") {

        $value = Yii::$app->request->get($name, $defaultValue);
        switch ($type) {
            case "number":
                $check_type= is_numeric($value);
                break;
            case "array":
                $check_type= is_array($value);
                break;
            default:
                $check_type=TRUE;
                break;
        }
        if(!$check_type){
            throw new SDPException("参数错误：传入的{$name}不是{$type}!");
        }
        return $value;
    }




    public function postParam($name,$defaultValue = NULL,$type="string") {

        $value = Yii::$app->request->post($name, $defaultValue);
        switch ($type) {
            case "number":
                $check_type= is_numeric($value);
                break;
            case "array":
                $check_type= is_array($value);
                break;
            default:
                $check_type=TRUE;
                break;
        }
        if(!$check_type){
            throw new SDPException("参数错误：传入的{$name}不是{$type}!");
        }
        return $value;
    }



}